#! /bin/bash
# generated by collect_git_add_recursively.sh

pushd $(dirname $0)                                                                                     2> /dev/null   > /dev/null
cd ..


mode="R"

Win7DEV_BASEDIR=/media/sf_D_DRIVE/h/prj/1original/SlickGrid/SlickGrid

function git_submod_add {
    git submodule  add $1 $2
    if test "$mode" = "W" ; then
        git_register_remote_for_UnixVM $1 $2
    fi
}

function git_register_remote_for_UnixVM {
    if test -d "$2" ; then
        if test -d "$Win7DEV_BASEDIR/$2" ; then
            pushd $2                                                                                    2> /dev/null  > /dev/null
            git remote remove Win7DEV
            git remote add Win7DEV $Win7DEV_BASEDIR/$2
            popd                                                                                        2> /dev/null  > /dev/null
        fi
    fi
}

getopts ":Wh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
W )
  echo "--- registering Win7DEV as remote ---"
  mode="W"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  if test -d "$1" ; then
    Win7DEV_BASEDIR=$1
  fi
  #
  # register Win7DEV remote for main repo as well!
  if test -d "$Win7DEV_BASEDIR" ; then
    git remote remove Win7DEV
    git remote add Win7DEV $Win7DEV_BASEDIR
  fi
  ;;

"?" )
  echo "--- registering git submodules ---"
  mode="R"
  ;;

* )
  cat <<EOT
$0 [-W <optional_remote_path>]

set up git submodules / submodule references for all submodules.

-W       : set up 'Win7DEV' remote reference per submodule

           When you don't specify the remote path yourself,
           the default is set to:
             "$Win7DEV_BASEDIR"

EOT
  exit
  ;;
esac




git_submod_add   git@github.com:GerHobbelt/SlickGrid.CheckboxSelectAllColumn.git         lib/slickgrid-checkbox-select-all-column-plugin
git_submod_add   git@github.com:GerHobbelt/SlickGrid.wiki.git                            documentation/wiki
git_submod_add   git@github.com:GerHobbelt/SlickGridEnhancementPager.git                 lib/slickgrid-enhanced-pager-plugin
git_submod_add   git@github.com:GerHobbelt/Surge-SlickGrid-Extensions.git                lib/slickgrid-surge-extensions
git_submod_add   git@github.com:GerHobbelt/TinyColor.git                                 lib/TinyColor
git_submod_add   git@github.com:GerHobbelt/datepick.git                                  lib/jquery-datepicker
git_submod_add   git@github.com:GerHobbelt/guriddo.git                                   lib/slickgrid-guriddo-frozencolumns
git_submod_add   git@github.com:GerHobbelt/hammer.js.git                                 lib/hammer
git_submod_add   git@github.com:GerHobbelt/jquery-multiselect.git                        lib/jquery-multiselect
git_submod_add   git@github.com:GerHobbelt/jquery-simulate.git                           lib/jquery-simulate
git_submod_add   git@github.com:GerHobbelt/jquery.sparkline.git                          lib/jquery-sparkline
git_submod_add   git@github.com:GerHobbelt/jquery.threedubmedia.git                      lib/threedubmedia
git_submod_add   git@github.com:GerHobbelt/keymaster.git                                 lib/keymaster
git_submod_add   git@github.com:GerHobbelt/slickgrid-spreadsheet-plugins.git             lib/slickgrid-spreadsheet-plugins
git_submod_add   git@github.com:GerHobbelt/slickgrid-totals-plugin.git                   lib/slickgrid-totals-plugin
git_submod_add   git@github.com:GerHobbelt/spectrum.git                                  lib/spectrum
git_submod_add   git@github.com:GerHobbelt/verge.git                                     lib/verge-screendimensions



popd                                                                                                    2> /dev/null   > /dev/null

