#! /bin/bash
# generated by collect_git_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote documentation/wiki                                            AMPTSalesSolutions                       git@github.com:AMPTSalesSolutions/SlickGrid.wiki.git                             $# $@
register_remote documentation/wiki                                            BlazeCell                                git@github.com:BlazeCell/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            CAnand                                   git@github.com:CAnand/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            Celebio                                  git@github.com:Celebio/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            ChadPrice                                git@github.com:ChadPrice/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            ClemensSchneider                         git@github.com:ClemensSchneider/SlickGrid.wiki.git                               $# $@
register_remote documentation/wiki                                            Craga89                                  git@github.com:Craga89/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            DataSplice                               git@github.com:DataSplice/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            DouglasMeyer                             git@github.com:DouglasMeyer/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            EdenRidgway                              git@github.com:EdenRidgway/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            FoxyGrid                                 git@github.com:FoxyGrid/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            GeoffTK                                  git@github.com:GeoffTK/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            GerHobbelt                               git@github.com:GerHobbelt/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            GustavSt                                 git@github.com:GustavSt/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            JLynch7                                  git@github.com:JLynch7/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            JimmyJune                                git@github.com:JimmyJune/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            JonBons                                  git@github.com:JonBons/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            Koloto                                   git@github.com:Koloto/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            Market7                                  git@github.com:Market7/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            MediaEquals                              git@github.com:MediaEquals/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            Mltroutt                                 git@github.com:Mltroutt/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            Morhaus                                  git@github.com:Morhaus/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            Moviri                                   git@github.com:Moviri/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            Mrmann87                                 git@github.com:Mrmann87/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            NeoSwf                                   git@github.com:NeoSwf/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            Odaeus                                   git@github.com:Odaeus/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            OrangeT                                  git@github.com:OrangeT/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            PerformanceHorizonGroup                  git@github.com:PerformanceHorizonGroup/SlickGrid.wiki.git                        $# $@
register_remote documentation/wiki                                            Polychart                                git@github.com:Polychart/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            RandScullard                             git@github.com:RandScullard/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            Rybadour                                 git@github.com:Rybadour/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            SimonBrangwin                            git@github.com:SimonBrangwin/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            SimpleAsCouldBe                          git@github.com:SimpleAsCouldBe/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            SlickGrid                                git@github.com:SlickGrid/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            SlickGrid-DraggableGrouping-SummaryFooters git@github.com:SlickGrid-DraggableGrouping-SummaryFooters/SlickGrid.wiki.git     $# $@
register_remote documentation/wiki                                            SlickGrid-Touch                          git@github.com:SlickGrid-Touch/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            SlickGrid-touch                          git@github.com:SlickGrid-touch/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            SpeCT                                    git@github.com:SpeCT/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            TNKSoftware                              git@github.com:TNKSoftware/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            TrevorRawlings                           git@github.com:TrevorRawlings/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            WanzhiTT                                 git@github.com:WanzhiTT/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            Yavanosta                                git@github.com:Yavanosta/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            YupengFu                                 git@github.com:YupengFu/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            ZiglioNZ                                 git@github.com:ZiglioNZ/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            a-romanov                                git@github.com:a-romanov/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            aemonge                                  git@github.com:aemonge/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            aflx                                     git@github.com:aflx/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            ajbrown                                  git@github.com:ajbrown/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            ajpiano                                  git@github.com:ajpiano/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            albaxe                                   git@github.com:albaxe/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            aleksj                                   git@github.com:aleksj/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            alexpusch                                git@github.com:alexpusch/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            alivedise                                git@github.com:alivedise/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            amdjs-SlickGrid                          git@github.com:amdjs-SlickGrid/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            andrewagga                               git@github.com:andrewagga/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            andrewchilds                             git@github.com:andrewchilds/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            bbuchalter                               git@github.com:bbuchalter/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            bigfix                                   git@github.com:bigfix/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            bighuggies                               git@github.com:bighuggies/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            blaremc                                  git@github.com:blaremc/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            bluesoft                                 git@github.com:bluesoft/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            borota                                   git@github.com:borota/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            borsosl                                  git@github.com:borsosl/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            bostonou                                 git@github.com:bostonou/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            brandonaaron                             git@github.com:brandonaaron/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            brettski74                               git@github.com:brettski74/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            brokenseal                               git@github.com:brokenseal/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            brondavies                               git@github.com:brondavies/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            bruce-sqlwork                            git@github.com:bruce-sqlwork/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            bruceharris                              git@github.com:bruceharris/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            bryandragon                              git@github.com:bryandragon/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            bug-buster                               git@github.com:bug-buster/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            centro                                   git@github.com:centro/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            chrisrichards                            git@github.com:chrisrichards/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            ciel-yu                                  git@github.com:ciel-yu/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            ckosmowski                               git@github.com:ckosmowski/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            cloud-solutions                          git@github.com:cloud-solutions/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            cmatheson                                git@github.com:cmatheson/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            cmpolis                                  git@github.com:cmpolis/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            cnkmym                                   git@github.com:cnkmym/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            cob                                      git@github.com:cob/SlickGrid.wiki.git                                            $# $@
register_remote documentation/wiki                                            cocbiz                                   git@github.com:cocbiz/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            codap-SlickGrid                          git@github.com:codap-SlickGrid/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            colinexl                                 git@github.com:colinexl/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            colorcyan                                git@github.com:colorcyan/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            colourblendcreative                      git@github.com:colourblendcreative/SlickGrid.wiki.git                            $# $@
register_remote documentation/wiki                                            concord-consortium                       git@github.com:concord-consortium/SlickGrid.wiki.git                             $# $@
register_remote documentation/wiki                                            csosborn                                 git@github.com:csosborn/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            czaks                                    git@github.com:czaks/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            danbroun                                 git@github.com:danbroun/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            dandv                                    git@github.com:dandv/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            dariusk                                  git@github.com:dariusk/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            davidkhess                               git@github.com:davidkhess/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            dbradicich                               git@github.com:dbradicich/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            ddomingues                               git@github.com:ddomingues/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            defunctzombie                            git@github.com:defunctzombie/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            dekajp                                   git@github.com:dekajp/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            dergraf                                  git@github.com:dergraf/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            dholcombe                                git@github.com:dholcombe/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            dominicbarnes                            git@github.com:dominicbarnes/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            dougma                                   git@github.com:dougma/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            drawyan                                  git@github.com:drawyan/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            drgnorq                                  git@github.com:drgnorq/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            dspiteself                               git@github.com:dspiteself/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            dtanabe                                  git@github.com:dtanabe/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            eea                                      git@github.com:eea/SlickGrid.wiki.git                                            $# $@
register_remote documentation/wiki                                            ejlo                                     git@github.com:ejlo/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            ekohe                                    git@github.com:ekohe/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            elwayman02                               git@github.com:elwayman02/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            emertechie                               git@github.com:emertechie/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            emilschutte                              git@github.com:emilschutte/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            ericmbarnard                             git@github.com:ericmbarnard/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            faizel                                   git@github.com:faizel/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            fatihsoydan                              git@github.com:fatihsoydan/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            fbuchinger                               git@github.com:fbuchinger/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            flashcloud                               git@github.com:flashcloud/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            flow38                                   git@github.com:flow38/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            fnordpig                                 git@github.com:fnordpig/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            frankguixianhua                          git@github.com:frankguixianhua/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            gcko                                     git@github.com:gcko/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            geriamir                                 git@github.com:geriamir/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            ghedwards                                git@github.com:ghedwards/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            gigi81                                   git@github.com:gigi81/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            gkostov                                  git@github.com:gkostov/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            graemian                                 git@github.com:graemian/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            gregor-rayman                            git@github.com:gregor-rayman/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            grooveshark                              git@github.com:grooveshark/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            halad                                    git@github.com:halad/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            hamza77500                               git@github.com:hamza77500/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            harbulot                                 git@github.com:harbulot/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            hariharanpalani                          git@github.com:hariharanpalani/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            henkli                                   git@github.com:henkli/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            hhutch                                   git@github.com:hhutch/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            hnakamur                                 git@github.com:hnakamur/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            ibrahimkarahan                           git@github.com:ibrahimkarahan/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            icambron                                 git@github.com:icambron/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            icoxfog417                               git@github.com:icoxfog417/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            igorT                                    git@github.com:igorT/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            ikarishinjieva                           git@github.com:ikarishinjieva/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            ikemirer                                 git@github.com:ikemirer/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            islamgulov                               git@github.com:islamgulov/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            j16sdiz                                  git@github.com:j16sdiz/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            jameshulse                               git@github.com:jameshulse/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            janek37                                  git@github.com:janek37/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            jbarlow83                                git@github.com:jbarlow83/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            jbthoma                                  git@github.com:jbthoma/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            jcook-logixml                            git@github.com:jcook-logixml/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            jcready                                  git@github.com:jcready/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            jcsjcs                                   git@github.com:jcsjcs/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            jeffreykwan                              git@github.com:jeffreykwan/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            jimgreco                                 git@github.com:jimgreco/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            joaoFelix                                git@github.com:joaoFelix/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            jolindqv                                 git@github.com:jolindqv/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            joshq00                                  git@github.com:joshq00/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            jroxendal                                git@github.com:jroxendal/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            jrschumacher                             git@github.com:jrschumacher/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            jsm222                                   git@github.com:jsm222/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            jstormes                                 git@github.com:jstormes/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            jupe                                     git@github.com:jupe/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            k0stya                                   git@github.com:k0stya/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            k2informatics                            git@github.com:k2informatics/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            kadamwhite                               git@github.com:kadamwhite/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            kmerz                                    git@github.com:kmerz/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            kubelsmieci                              git@github.com:kubelsmieci/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            kzhdev                                   git@github.com:kzhdev/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            laripk                                   git@github.com:laripk/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            littlebee                                git@github.com:littlebee/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            loris                                    git@github.com:loris/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            lvanderbijl                              git@github.com:lvanderbijl/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            magiconair                               git@github.com:magiconair/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            mario-areias                             git@github.com:mario-areias/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            marioandujar                             git@github.com:marioandujar/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            mastropinguino                           git@github.com:mastropinguino/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            matthieu-ravey                           git@github.com:matthieu-ravey/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            mckramer                                 git@github.com:mckramer/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            meetmauro                                git@github.com:meetmauro/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            merkushov                                git@github.com:merkushov/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            meyogi                                   git@github.com:meyogi/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            milichev                                 git@github.com:milichev/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            minhajuddin                              git@github.com:minhajuddin/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            mleibman                                 git@github.com:mleibman/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            mleibman-original                        git@github.com:mleibman/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            momaci                                   git@github.com:momaci/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            mplorentz                                git@github.com:mplorentz/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            mr-stateradio                            git@github.com:mr-stateradio/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            mrigi                                    git@github.com:mrigi/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            mruflin                                  git@github.com:mruflin/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            mtscout6                                 git@github.com:mtscout6/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            mujhs                                    git@github.com:mujhs/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            nathanstiles                             git@github.com:nathanstiles/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            nathasm                                  git@github.com:nathasm/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            nbaksalyar                               git@github.com:nbaksalyar/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            nilcolor                                 git@github.com:nilcolor/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            omixen                                   git@github.com:omixen/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            oshea00                                  git@github.com:oshea00/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            overloop                                 git@github.com:overloop/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            pandell                                  git@github.com:pandell/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            paul-lysak                               git@github.com:paul-lysak/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            pauleveritt                              git@github.com:pauleveritt/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            paulsfds                                 git@github.com:paulsfds/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            peterlevi                                git@github.com:peterlevi/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            pombredanne                              git@github.com:pombredanne/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            popbee                                   git@github.com:popbee/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            prystupa                                 git@github.com:prystupa/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            ptraca                                   git@github.com:ptraca/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            pythonanywhere                           git@github.com:pythonanywhere/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            rafi                                     git@github.com:rafi/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            reebalazs                                git@github.com:reebalazs/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            resnyanskiy                              git@github.com:resnyanskiy/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            richardcrichardc                         git@github.com:richardcrichardc/SlickGrid.wiki.git                               $# $@
register_remote documentation/wiki                                            rnarayana                                git@github.com:rnarayana/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            ronmichael                               git@github.com:ronmichael/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            rootnot                                  git@github.com:rootnot/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            ruchi8                                   git@github.com:ruchi8/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            ryanramage                               git@github.com:ryanramage/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            saks                                     git@github.com:saks/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            sbimbra                                  git@github.com:sbimbra/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            seriesoftubes                            git@github.com:seriesoftubes/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            sivasakki                                git@github.com:sivasakki/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            slickgrid                                git@github.com:slickgrid/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            snies                                    git@github.com:snies/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            sonatype                                 git@github.com:sonatype/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            sortex                                   git@github.com:sortex/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            ssafejava                                git@github.com:ssafejava/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            sstergou                                 git@github.com:sstergou/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            stanislavgeorgiev                        git@github.com:stanislavgeorgiev/SlickGrid.wiki.git                              $# $@
register_remote documentation/wiki                                            stozze                                   git@github.com:stozze/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            streamlinesocial                         git@github.com:streamlinesocial/SlickGrid.wiki.git                               $# $@
register_remote documentation/wiki                                            stsamuel                                 git@github.com:stsamuel/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            svieira                                  git@github.com:svieira/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            taskputty                                git@github.com:taskputty/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            tavanttpuser                             git@github.com:tavanttpuser/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            tblohorn                                 git@github.com:tblohorn/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            teleological                             git@github.com:teleological/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            thickey                                  git@github.com:thickey/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            thurloat                                 git@github.com:thurloat/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            thurn                                    git@github.com:thurn/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            timkuijsten                              git@github.com:timkuijsten/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            tjormola                                 git@github.com:tjormola/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            tobya                                    git@github.com:tobya/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            topherchristie                           git@github.com:topherchristie/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            toreba                                   git@github.com:toreba/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            tradingtechnologies                      git@github.com:tradingtechnologies/SlickGrid.wiki.git                            $# $@
register_remote documentation/wiki                                            trasa                                    git@github.com:trasa/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            truehot                                  git@github.com:truehot/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            truk                                     git@github.com:truk/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            vdsabev                                  git@github.com:vdsabev/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            vladkosarev                              git@github.com:vladkosarev/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            vlsi                                     git@github.com:vlsi/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            vyrak                                    git@github.com:vyrak/SlickGrid.wiki.git                                          $# $@
register_remote documentation/wiki                                            waterfield                               git@github.com:waterfield/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            waynebloss                               git@github.com:waynebloss/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            wm                                       git@github.com:wm/SlickGrid.wiki.git                                             $# $@
register_remote documentation/wiki                                            xrmx                                     git@github.com:xrmx/SlickGrid.wiki.git                                           $# $@
register_remote documentation/wiki                                            yakirmanor                               git@github.com:yakirmanor/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            yanavery                                 git@github.com:yanavery/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            yokkaichi                                git@github.com:yokkaichi/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            yolpsoftware                             git@github.com:yolpsoftware/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            zhiyiw                                   git@github.com:zhiyiw/SlickGrid.wiki.git                                         $# $@
register_remote lib/threedubmedia                                             master-submodule                         ../../../jquery-event-drag-drop/                                                 $# $@
register_remote lib/threedubmedia                                             master-submodule-original                ../../../jquery-event-drag-drop/                                                 $# $@



popd                                                                            2> /dev/null   > /dev/null

