#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote documentation/wiki                                            Celebio                                  git@github.com:Celebio/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            GerHobbelt                               git@github.com:GerHobbelt/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            JLynch7                                  git@github.com:JLynch7/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            JonBons                                  git@github.com:JonBons/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            Market7                                  git@github.com:Market7/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            Moviri                                   git@github.com:Moviri/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            Odaeus                                   git@github.com:Odaeus/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            Rybadour                                 git@github.com:Rybadour/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            TrevorRawlings                           git@github.com:TrevorRawlings/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            andrewchilds                             git@github.com:andrewchilds/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            borota                                   git@github.com:borota/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            bruceharris                              git@github.com:bruceharris/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            chrisrichards                            git@github.com:chrisrichards/SlickGrid.wiki.git                                  $# $@
register_remote documentation/wiki                                            ciel-yu                                  git@github.com:ciel-yu/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            ckosmowski                               git@github.com:ckosmowski/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            conwin                                   git@github.com:conwin/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            ddomingues                               git@github.com:ddomingues/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            dergraf                                  git@github.com:dergraf/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            dholcombe                                git@github.com:dholcombe/SlickGrid.wiki.git                                      $# $@
register_remote documentation/wiki                                            eea                                      git@github.com:eea/SlickGrid.wiki.git                                            $# $@
register_remote documentation/wiki                                            geriamir                                 git@github.com:geriamir/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            hariharanpalani                          git@github.com:hariharanpalani/SlickGrid.wiki.git                                $# $@
register_remote documentation/wiki                                            ibrahimkarahan                           git@github.com:ibrahimkarahan/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            kzhdev                                   git@github.com:kzhdev/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            marioandujar                             git@github.com:marioandujar/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            mleibman                                 git@github.com:mleibman/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            mleibman-original                        git@github.com:mleibman/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            mtscout6                                 git@github.com:mtscout6/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            nathanstiles                             git@github.com:nathanstiles/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            paul-lysak                               git@github.com:paul-lysak/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            resnyanskiy                              git@github.com:resnyanskiy/SlickGrid.wiki.git                                    $# $@
register_remote documentation/wiki                                            roopali8                                 git@github.com:roopali8/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            rootnot                                  git@github.com:rootnot/SlickGrid.wiki.git                                        $# $@
register_remote documentation/wiki                                            ruchi8                                   git@github.com:ruchi8/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            sortex                                   git@github.com:sortex/SlickGrid.wiki.git                                         $# $@
register_remote documentation/wiki                                            stsamuel                                 git@github.com:stsamuel/SlickGrid.wiki.git                                       $# $@
register_remote documentation/wiki                                            topherchristie                           git@github.com:topherchristie/SlickGrid.wiki.git                                 $# $@
register_remote documentation/wiki                                            tradingtechnologies                      git@github.com:tradingtechnologies/SlickGrid.wiki.git                            $# $@
register_remote documentation/wiki                                            waterfield                               git@github.com:waterfield/SlickGrid.wiki.git                                     $# $@
register_remote documentation/wiki                                            yolpsoftware                             git@github.com:yolpsoftware/SlickGrid.wiki.git                                   $# $@
register_remote documentation/wiki                                            zhiyiw                                   git@github.com:zhiyiw/SlickGrid.wiki.git                                         $# $@
register_remote lib/TinyColor                                                 Bantam                                   git@github.com:Bantam/TinyColor.git                                              $# $@
register_remote lib/TinyColor                                                 DennisKehrig                             git@github.com:DennisKehrig/TinyColor.git                                        $# $@
register_remote lib/TinyColor                                                 GerHobbelt                               git@github.com:GerHobbelt/TinyColor.git                                          $# $@
register_remote lib/TinyColor                                                 IwanLuijksQuestMedia                     git@github.com:IwanLuijksQuestMedia/TinyColor.git                                $# $@
register_remote lib/TinyColor                                                 Lewiscowles1986                          git@github.com:Lewiscowles1986/TinyColor.git                                     $# $@
register_remote lib/TinyColor                                                 Saulis                                   git@github.com:Saulis/TinyColor.git                                              $# $@
register_remote lib/TinyColor                                                 Y--                                      git@github.com:Y--/TinyColor.git                                                 $# $@
register_remote lib/TinyColor                                                 aaronm67                                 git@github.com:aaronm67/TinyColor.git                                            $# $@
register_remote lib/TinyColor                                                 andersondo                               git@github.com:andersondo/TinyColor.git                                          $# $@
register_remote lib/TinyColor                                                 aramk                                    git@github.com:aramk/TinyColor.git                                               $# $@
register_remote lib/TinyColor                                                 autopulated                              git@github.com:autopulated/TinyTinyColor.git                                     $# $@
register_remote lib/TinyColor                                                 bgrins                                   git@github.com:bgrins/TinyColor.git                                              $# $@
register_remote lib/TinyColor                                                 bgrins-original                          git@github.com:GerHobbelt/TinyColor.git                                          $# $@
register_remote lib/TinyColor                                                 biovisualize                             git@github.com:biovisualize/TinyColor.git                                        $# $@
register_remote lib/TinyColor                                                 gjtorikian                               git@github.com:gjtorikian/TinyColor.git                                          $# $@
register_remote lib/TinyColor                                                 haoliu119                                git@github.com:haoliu119/TinyColor.git                                           $# $@
register_remote lib/TinyColor                                                 jladbury                                 git@github.com:jladbury/TinyColor.git                                            $# $@
register_remote lib/TinyColor                                                 local-dep-original                       ../../../TinyColor/                                                              $# $@
register_remote lib/TinyColor                                                 local-dep-spectrum-original              ../spectrum/lib/TinyColor/                                                       $# $@
register_remote lib/TinyColor                                                 local-original                           ../../../TinyColor/                                                              $# $@
register_remote lib/TinyColor                                                 pgooch                                   git@github.com:pgooch/TinyColor.git                                              $# $@
register_remote lib/TinyColor                                                 piercus                                  git@github.com:piercus/TinyColor.git                                             $# $@
register_remote lib/TinyColor                                                 spectrum-dep-original                    ../spectrum/lib/TinyColor/                                                       $# $@
register_remote lib/TinyColor                                                 trevorlinton                             git@github.com:trevorlinton/TinyColor.git                                        $# $@
register_remote lib/TinyColor                                                 tylerl                                   git@github.com:tylerl/TinyColor.git                                              $# $@
register_remote lib/hammer                                                    EightMedia                               git@github.com:EightMedia/hammer.js.git                                          $# $@
register_remote lib/hammer                                                    EightMedia-original                      git@github.com:EightMedia/hammer.js.git                                          $# $@
register_remote lib/hammer                                                    HumbleSoftware                           git@github.com:HumbleSoftware/hammer.js.git                                      $# $@
register_remote lib/hammer                                                    Prinzhorn                                git@github.com:Prinzhorn/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    QzhouZ                                   git@github.com:QzhouZ/hammer.js.git                                              $# $@
register_remote lib/hammer                                                    Stereobit                                git@github.com:Stereobit/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    abiank                                   git@github.com:abiank/hammer.js.git                                              $# $@
register_remote lib/hammer                                                    acc3ptC                                  git@github.com:acc3ptC/hammer.js.git                                             $# $@
register_remote lib/hammer                                                    adrianmaurer                             git@github.com:adrianmaurer/hammer.js.git                                        $# $@
register_remote lib/hammer                                                    albertogasparin                          git@github.com:albertogasparin/hammer.js.git                                     $# $@
register_remote lib/hammer                                                    artch                                    git@github.com:artch/hammer.js.git                                               $# $@
register_remote lib/hammer                                                    brian-frichette                          git@github.com:brian-frichette/hammer.js.git                                     $# $@
register_remote lib/hammer                                                    cinema6                                  git@github.com:cinema6/hammer.js.git                                             $# $@
register_remote lib/hammer                                                    component                                git@github.com:component/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    ctfzh                                    git@github.com:ctfzh/hammer.js.git                                               $# $@
register_remote lib/hammer                                                    defunctzombie                            git@github.com:defunctzombie/hammer.js.git                                       $# $@
register_remote lib/hammer                                                    dmikis                                   git@github.com:dmikis/hammer.js.git                                              $# $@
register_remote lib/hammer                                                    encuestame                               git@github.com:encuestame/hammer.js.git                                          $# $@
register_remote lib/hammer                                                    fellyph                                  git@github.com:fellyph/hammer.js.git                                             $# $@
register_remote lib/hammer                                                    hosup                                    git@github.com:hosup/hammer.js.git                                               $# $@
register_remote lib/hammer                                                    hotzenklotz                              git@github.com:hotzenklotz/hammer.js.git                                         $# $@
register_remote lib/hammer                                                    jasonjohnson-wf                          git@github.com:jasonjohnson-wf/hammer.js.git                                     $# $@
register_remote lib/hammer                                                    jstrimpel                                git@github.com:jstrimpel/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    lge88                                    git@github.com:lge88/hammer.js.git                                               $# $@
register_remote lib/hammer                                                    lloiser                                  git@github.com:lloiser/hammer.js.git                                             $# $@
register_remote lib/hammer                                                    local-original                           ../../../hammer                                                                  $# $@
register_remote lib/hammer                                                    lucasgunn                                git@github.com:lucasgunn/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    lukaszlipinski                           git@github.com:lukaszlipinski/hammer.js.git                                      $# $@
register_remote lib/hammer                                                    lukewestby                               git@github.com:lukewestby/hammer.js.git                                          $# $@
register_remote lib/hammer                                                    marioestrada                             git@github.com:marioestrada/hammer.js.git                                        $# $@
register_remote lib/hammer                                                    mhaugland                                git@github.com:mhaugland/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    monospaced                               git@github.com:monospaced/hammer.js.git                                          $# $@
register_remote lib/hammer                                                    nextime                                  git@github.com:nextime/hammer.js.git                                             $# $@
register_remote lib/hammer                                                    phated                                   git@github.com:phated/hammer.js.git                                              $# $@
register_remote lib/hammer                                                    pichfl                                   git@github.com:pichfl/hammer.js.git                                              $# $@
register_remote lib/hammer                                                    prashantpawar                            git@github.com:prashantpawar/hammer.js.git                                       $# $@
register_remote lib/hammer                                                    rdio                                     git@github.com:rdio/hammer.js.git                                                $# $@
register_remote lib/hammer                                                    rhoffmann                                git@github.com:rhoffmann/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    saidai-no                                git@github.com:saidai-no/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    samuelhorwitz                            git@github.com:samuelhorwitz/hammer.js.git                                       $# $@
register_remote lib/hammer                                                    schmidsi                                 git@github.com:schmidsi/hammer.js.git                                            $# $@
register_remote lib/hammer                                                    sellig                                   git@github.com:sellig/hammer.js.git                                              $# $@
register_remote lib/hammer                                                    shirmung                                 git@github.com:shirmung/hammer.js.git                                            $# $@
register_remote lib/hammer                                                    simonbetton                              git@github.com:simonbetton/hammer.js.git                                         $# $@
register_remote lib/hammer                                                    skynet                                   git@github.com:skynet/hammer.js.git                                              $# $@
register_remote lib/hammer                                                    soulman72                                git@github.com:soulman72/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    the-machinist                            git@github.com:the-machinist/hammer.js.git                                       $# $@
register_remote lib/hammer                                                    thoughtco                                git@github.com:thoughtco/hammer.js.git                                           $# $@
register_remote lib/hammer                                                    tjsnyder                                 git@github.com:tjsnyder/hammer.js.git                                            $# $@
register_remote lib/hammer                                                    visionmedia                              git@github.com:visionmedia/hammer.js.git                                         $# $@
register_remote lib/hammer                                                    vladgurovich                             git@github.com:vladgurovich/hammer.js.git                                        $# $@
register_remote lib/hammer                                                    wilson1315                               git@github.com:wilson1315/hammer.js.git                                          $# $@
register_remote lib/jquery-fixclick                                           GerHobbelt-original                      git@github.com:GerHobbelt/jquery-fixclick.git                                    $# $@
register_remote lib/jquery-iCheck                                             0x0all                                   git@github.com:0x0all/iCheck.git                                                 $# $@
register_remote lib/jquery-iCheck                                             AustinTsai                               git@github.com:AustinTsai/iCheck.git                                             $# $@
register_remote lib/jquery-iCheck                                             applepicke                               git@github.com:applepicke/iCheck.git                                             $# $@
register_remote lib/jquery-iCheck                                             bart                                     git@github.com:bart/iCheck.git                                                   $# $@
register_remote lib/jquery-iCheck                                             benmliang                                git@github.com:benmliang/angular-iCheck.git                                      $# $@
register_remote lib/jquery-iCheck                                             bontaq                                   git@github.com:bontaq/iCheck.git                                                 $# $@
register_remote lib/jquery-iCheck                                             cornellsteven                            git@github.com:cornellsteven/iCheck-Zepto.git                                    $# $@
register_remote lib/jquery-iCheck                                             countersoft                              git@github.com:countersoft/iCheck.git                                            $# $@
register_remote lib/jquery-iCheck                                             davojta                                  git@github.com:davojta/iCheck.git                                                $# $@
register_remote lib/jquery-iCheck                                             dennisdevetter                           git@github.com:dennisdevetter/iCheck.git                                         $# $@
register_remote lib/jquery-iCheck                                             foocoop                                  git@github.com:foocoop/iCheck.git                                                $# $@
register_remote lib/jquery-iCheck                                             fronteed                                 git@github.com:fronteed/iCheck.git                                               $# $@
register_remote lib/jquery-iCheck                                             fronteed-original                        git@github.com:fronteed/iCheck.git                                               $# $@
register_remote lib/jquery-iCheck                                             ghispi                                   git@github.com:ghispi/iCheck.git                                                 $# $@
register_remote lib/jquery-iCheck                                             jmoraleda                                git@github.com:jmoraleda/iCheck.git                                              $# $@
register_remote lib/jquery-iCheck                                             ktgit                                    git@github.com:ktgit/iCheck.git                                                  $# $@
register_remote lib/jquery-iCheck                                             mastodonte                               git@github.com:mastodonte/iCheck.git                                             $# $@
register_remote lib/jquery-iCheck                                             mike-mcgann                              git@github.com:mike-mcgann/iCheck.git                                            $# $@
register_remote lib/jquery-iCheck                                             nasaorc                                  git@github.com:nasaorc/iCheck.git                                                $# $@
register_remote lib/jquery-iCheck                                             pYr0x                                    git@github.com:pYr0x/iCheck.git                                                  $# $@
register_remote lib/jquery-iCheck                                             sbaechler                                git@github.com:sbaechler/iCheck.git                                              $# $@
register_remote lib/jquery-iCheck                                             tagliala                                 git@github.com:tagliala/iCheck.git                                               $# $@
register_remote lib/jquery-iCheck                                             vedyakov                                 git@github.com:vedyakov/iCheck.git                                               $# $@
register_remote lib/jquery-iCheck                                             wefiy                                    git@github.com:wefiy/iCheck.git                                                  $# $@
register_remote lib/jquery-iCheck                                             yc2164708                                git@github.com:yc2164708/iCheck.git                                              $# $@
register_remote lib/jquery-iCheck                                             ziscloud                                 git@github.com:ziscloud/iCheck.git                                               $# $@
register_remote lib/jquery-jsonp                                              ZeeD                                     git@github.com:ZeeD/jquery-jsonp.git                                             $# $@
register_remote lib/jquery-jsonp                                              basos9                                   git@github.com:basos9/jquery-jsonp.git                                           $# $@
register_remote lib/jquery-jsonp                                              calebclark                               git@github.com:calebclark/jquery-jsonp.git                                       $# $@
register_remote lib/jquery-jsonp                                              collinanderson                           git@github.com:collinanderson/jquery-jsonp.git                                   $# $@
register_remote lib/jquery-jsonp                                              fivetanley                               git@github.com:fivetanley/jquery-jsonp.git                                       $# $@
register_remote lib/jquery-jsonp                                              hanguyenst                               git@github.com:hanguyenst/jquery-jsonp.git                                       $# $@
register_remote lib/jquery-jsonp                                              hull                                     git@github.com:hull/jquery-jsonp.git                                             $# $@
register_remote lib/jquery-jsonp                                              jaubourg                                 git@github.com:jaubourg/jquery-jsonp.git                                         $# $@
register_remote lib/jquery-jsonp                                              jaubourg-original                        git@github.com:jaubourg/jquery-jsonp.git                                         $# $@
register_remote lib/jquery-jsonp                                              timtucker                                git@github.com:timtucker/jquery-jsonp.git                                        $# $@
register_remote lib/jquery-jsonp                                              zamesnonet                               git@github.com:zamesnonet/jquery-jsonp.git                                       $# $@
register_remote lib/jquery-migrate                                            AlvinHan                                 git@github.com:AlvinHan/jquery-migrate.git                                       $# $@
register_remote lib/jquery-migrate                                            Garethderioth                            git@github.com:Garethderioth/jquery-migrate.git                                  $# $@
register_remote lib/jquery-migrate                                            InterNations                             git@github.com:InterNations/jquery-migrate.git                                   $# $@
register_remote lib/jquery-migrate                                            aakoch                                   git@github.com:aakoch/jquery-migrate.git                                         $# $@
register_remote lib/jquery-migrate                                            gibson042                                git@github.com:gibson042/jquery-migrate.git                                      $# $@
register_remote lib/jquery-migrate                                            jquery                                   git@github.com:jquery/jquery-migrate.git                                         $# $@
register_remote lib/jquery-migrate                                            jquery-original                          git@github.com:jquery/jquery-migrate.git                                         $# $@
register_remote lib/jquery-migrate                                            kavu                                     git@github.com:kavu/jquery-migrate.git                                           $# $@
register_remote lib/jquery-migrate                                            leobalter                                git@github.com:leobalter/jquery-migrate.git                                      $# $@
register_remote lib/jquery-migrate                                            mattbrundage                             git@github.com:mattbrundage/jquery-migrate.git                                   $# $@
register_remote lib/jquery-migrate                                            nacin                                    git@github.com:nacin/jquery-migrate.git                                          $# $@
register_remote lib/jquery-migrate                                            nicoder                                  git@github.com:nicoder/jquery-migrate.git                                        $# $@
register_remote lib/jquery-migrate                                            scottgonzalez                            git@github.com:scottgonzalez/jquery-migrate.git                                  $# $@
register_remote lib/jquery-migrate                                            silentroach                              git@github.com:silentroach/jquery-migrate.git                                    $# $@
register_remote lib/jquery-migrate                                            wbinnssmith                              git@github.com:wbinnssmith/jquery-migrate.git                                    $# $@
register_remote lib/jquery-multiselect                                        0plus1                                   git@github.com:0plus1/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        AquaSwami                                git@github.com:AquaSwami/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        BangBoy                                  git@github.com:BangBoy/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        ChadSikorra                              git@github.com:ChadSikorra/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        CodeCommander                            git@github.com:CodeCommander/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        ConvMe                                   git@github.com:ConvMe/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        DaleKocian                               git@github.com:DaleKocian/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        Dan-Nolan                                git@github.com:Dan-Nolan/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        DarkAvanger                              git@github.com:DarkAvanger/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        Data-Dev-Team                            git@github.com:Data-Dev-Team/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        EleotleCram                              git@github.com:EleotleCram/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        GerHobbelt                               git@github.com:GerHobbelt/jquery-multiselect.git                                 $# $@
register_remote lib/jquery-multiselect                                        GerHobbelt-UI                            git@github.com:GerHobbelt/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        KarneAsada                               git@github.com:KarneAsada/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        MateuszKuriata                           git@github.com:MateuszKuriata/jquery-ui-multiselect-widget.git                   $# $@
register_remote lib/jquery-multiselect                                        NationalResearchCorporation              git@github.com:NationalResearchCorporation/jquery-ui-multiselect-widget.git      $# $@
register_remote lib/jquery-multiselect                                        Nextt                                    git@github.com:Nextt/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        PieroWbmstr                              git@github.com:PieroWbmstr/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        RappsFF7                                 git@github.com:RappsFF7/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        RocShow                                  git@github.com:RocShow/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        RuthElia                                 git@github.com:RuthElia/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        TerryMooreII                             git@github.com:TerryMooreII/jquery-ui-multiselect-widget.git                     $# $@
register_remote lib/jquery-multiselect                                        TheBosZ                                  git@github.com:TheBosZ/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        TrainingPeaks                            git@github.com:TrainingPeaks/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        adamli                                   git@github.com:adamli/jquery-multiselect.git                                     $# $@
register_remote lib/jquery-multiselect                                        aerichmond                               git@github.com:aerichmond/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        aetchegoyen                              git@github.com:aetchegoyen/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        afortaleza                               git@github.com:afortaleza/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        alexeyramazanov                          git@github.com:alexeyramazanov/jquery-ui-multiselect-widget.git                  $# $@
register_remote lib/jquery-multiselect                                        aplacito-original                        git@github.com:aplacito/jquery-multiselect.git                                   $# $@
register_remote lib/jquery-multiselect                                        apuratepp                                git@github.com:apuratepp/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        benikov                                  git@github.com:benikov/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        bwlang                                   git@github.com:bwlang/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        c41                                      git@github.com:c41/jquery-ui-multiselect-widget.git                              $# $@
register_remote lib/jquery-multiselect                                        cedriclombardot                          git@github.com:cedriclombardot/jquery-ui-multiselect-widget.git                  $# $@
register_remote lib/jquery-multiselect                                        coke                                     git@github.com:coke/jquery-ui-multiselect-widget.git                             $# $@
register_remote lib/jquery-multiselect                                        cstewart87                               git@github.com:cstewart87/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        dabdine                                  git@github.com:dabdine/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        danenania                                git@github.com:danenania/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        davehermann                              git@github.com:davehermann/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        davidworkman9                            git@github.com:davidworkman9/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        denis111                                 git@github.com:denis111/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        dobozysaurus                             git@github.com:dobozysaurus/jquery-ui-multiselect-widget.git                     $# $@
register_remote lib/jquery-multiselect                                        doits                                    git@github.com:doits/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        easytomanage                             git@github.com:easytomanage/jquery-ui-multiselect-widget.git                     $# $@
register_remote lib/jquery-multiselect                                        ecappa                                   git@github.com:ecappa/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        ehynds                                   git@github.com:ehynds/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        ehynds-original                          git@github.com:ehynds/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        ehynds-updated                           git@github.com:ehynds/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        ericpanorel                              git@github.com:ericpanorel/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        exu                                      git@github.com:exu/jquery-ui-multiselect-widget.git                              $# $@
register_remote lib/jquery-multiselect                                        franmomu                                 git@github.com:franmomu/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        ghasem                                   git@github.com:ghasem/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        hernant                                  git@github.com:hernant/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        ismailbaskin                             git@github.com:ismailbaskin/jquery-ui-multiselect-widget.git                     $# $@
register_remote lib/jquery-multiselect                                        jgeurts                                  git@github.com:jgeurts/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        jiangxianfu                              git@github.com:jiangxianfu/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        jons                                     git@github.com:jons/jquery-ui-multiselect-widget.git                             $# $@
register_remote lib/jquery-multiselect                                        joshdance                                git@github.com:joshdance/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        jpofl                                    git@github.com:jpofl/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        julesbravo                               git@github.com:julesbravo/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        justjohn                                 git@github.com:justjohn/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        kccarter                                 git@github.com:kccarter/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        kccarter76                               git@github.com:kccarter76/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        kielni                                   git@github.com:kielni/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        krootee                                  git@github.com:krootee/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        ledkk                                    git@github.com:ledkk/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        lhoeppner                                git@github.com:lhoeppner/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        lion19                                   git@github.com:lion19/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        local-original                           ../../../jquery-multiselect                                                      $# $@
register_remote lib/jquery-multiselect                                        macku                                    git@github.com:macku/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        mantici                                  git@github.com:mantici/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        mareczek                                 git@github.com:mareczek/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        matthayes                                git@github.com:matthayes/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        mcl-de                                   git@github.com:mcl-de/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        mmathieum                                git@github.com:mmathieum/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        mppfiles                                 git@github.com:mppfiles/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        musay                                    git@github.com:musay/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        northwood                                git@github.com:northwood/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        pandamouse                               git@github.com:pandamouse/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        pawel-piskorz                            git@github.com:pawel-piskorz/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        peiwei                                   git@github.com:peiwei/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        perkof                                   git@github.com:perkof/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        peytons                                  git@github.com:peytons/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        pinnymz                                  git@github.com:pinnymz/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        poquelicot                               git@github.com:poquelicot/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        ppanthony                                git@github.com:ppanthony/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        r4j4h                                    git@github.com:r4j4h/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        richard-ive-m4                           git@github.com:richard-ive-m4/jquery-ui-multiselect-widget.git                   $# $@
register_remote lib/jquery-multiselect                                        rigobcastro                              git@github.com:rigobcastro/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        rrusnak1                                 git@github.com:rrusnak1/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        saggim                                   git@github.com:saggim/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        seferov                                  git@github.com:seferov/jquery-ui-multiselect-widget.git                          $# $@
register_remote lib/jquery-multiselect                                        sgonzalez3884                            git@github.com:sgonzalez3884/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        shakirshakiel                            git@github.com:shakirshakiel/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        simauria                                 git@github.com:simauria/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        sleimbro                                 git@github.com:sleimbro/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        spidasoftware                            git@github.com:spidasoftware/jquery-ui-multiselect-widget.git                    $# $@
register_remote lib/jquery-multiselect                                        supermarcos                              git@github.com:supermarcos/jquery-ui-multiselect-widget.git                      $# $@
register_remote lib/jquery-multiselect                                        tapmantwo                                git@github.com:tapmantwo/jquery-ui-multiselect-widget.git                        $# $@
register_remote lib/jquery-multiselect                                        tdakanalis                               git@github.com:tdakanalis/jquery-ui-multiselect-widget.git                       $# $@
register_remote lib/jquery-multiselect                                        tellibus                                 git@github.com:tellibus/jquery-ui-multiselect-widget.git                         $# $@
register_remote lib/jquery-multiselect                                        thelinuxlich                             git@github.com:thelinuxlich/jquery-ui-multiselect-widget.git                     $# $@
register_remote lib/jquery-multiselect                                        vergil                                   git@github.com:vergil/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        viict                                    git@github.com:viict/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        vmtco                                    git@github.com:vmtco/jquery-ui-multiselect-widget.git                            $# $@
register_remote lib/jquery-multiselect                                        wulis8                                   git@github.com:wulis8/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-multiselect                                        zlamma                                   git@github.com:zlamma/jquery-ui-multiselect-widget.git                           $# $@
register_remote lib/jquery-simulate                                           GerHobbelt                               git@github.com:GerHobbelt/jquery-simulate.git                                    $# $@
register_remote lib/jquery-simulate                                           NightfireRed                             git@github.com:NightfireRed/jquery-simulate.git                                  $# $@
register_remote lib/jquery-simulate                                           adjohnson916                             git@github.com:adjohnson916/jquery-simulate.git                                  $# $@
register_remote lib/jquery-simulate                                           adrianchen19888                          git@github.com:adrianchen19888/jquery-simulate.git                               $# $@
register_remote lib/jquery-simulate                                           cyril-sf                                 git@github.com:cyril-sf/jquery-simulate.git                                      $# $@
register_remote lib/jquery-simulate                                           duselmann                                git@github.com:duselmann/jquery-simulate.git                                     $# $@
register_remote lib/jquery-simulate                                           eduardolundgren                          git@github.com:eduardolundgren/jquery-simulate.git                               $# $@
register_remote lib/jquery-simulate                                           heathn                                   git@github.com:heathn/jquery-simulate.git                                        $# $@
register_remote lib/jquery-simulate                                           johnkpaul                                git@github.com:johnkpaul/jquery-simulate.git                                     $# $@
register_remote lib/jquery-simulate                                           jquery                                   git@github.com:jquery/jquery-simulate.git                                        $# $@
register_remote lib/jquery-simulate                                           jquery-original                          git@github.com:jquery/jquery-simulate.git                                        $# $@
register_remote lib/jquery-simulate                                           larslaade                                git@github.com:larslaade/jquery-simulate.git                                     $# $@
register_remote lib/jquery-simulate                                           local-original                           ../../../jquery-simulate                                                         $# $@
register_remote lib/jquery-simulate                                           mpetozzi                                 git@github.com:mpetozzi/jquery-simulate.git                                      $# $@
register_remote lib/jquery-simulate                                           pscheit                                  git@github.com:pscheit/jquery-simulate.git                                       $# $@
register_remote lib/jquery-simulate                                           robkinyon                                git@github.com:robkinyon/jquery-simulate.git                                     $# $@
register_remote lib/jquery-simulate                                           salomvary                                git@github.com:salomvary/jquery-simulate.git                                     $# $@
register_remote lib/jquery-simulate                                           scottgonzalez                            git@github.com:scottgonzalez/jquery-simulate.git                                 $# $@
register_remote lib/jquery-simulate                                           steveluscher                             git@github.com:steveluscher/jquery-simulate.git                                  $# $@
register_remote lib/jquery-simulate                                           vincecarney                              git@github.com:vincecarney/jquery-simulate.git                                   $# $@
register_remote lib/jquery-sparkline                                          GerHobbelt                               git@github.com:GerHobbelt/jquery.sparkline.git                                   $# $@
register_remote lib/jquery-sparkline                                          PeerCDN                                  git@github.com:PeerCDN/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline                                          aguynamedryan                            git@github.com:aguynamedryan/jquery.sparkline.git                                $# $@
register_remote lib/jquery-sparkline                                          andreala                                 git@github.com:andreala/jquery.sparkline.git                                     $# $@
register_remote lib/jquery-sparkline                                          andykellr                                git@github.com:andykellr/jquery.sparkline.git                                    $# $@
register_remote lib/jquery-sparkline                                          clody69                                  git@github.com:clody69/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline                                          cthrax                                   git@github.com:cthrax/jquery.sparkline.git                                       $# $@
register_remote lib/jquery-sparkline                                          ericburns                                git@github.com:ericburns/jquery.sparkline.git                                    $# $@
register_remote lib/jquery-sparkline                                          fabianvo                                 git@github.com:fabianvo/jquery.sparkline.git                                     $# $@
register_remote lib/jquery-sparkline                                          fangjianbin                              git@github.com:fangjianbin/jquery.sparkline.git                                  $# $@
register_remote lib/jquery-sparkline                                          foundry-modules                          git@github.com:foundry-modules/jquery.sparkline.git                              $# $@
register_remote lib/jquery-sparkline                                          gwatts-original                          git@github.com:gwatts/jquery.sparkline.git                                       $# $@
register_remote lib/jquery-sparkline                                          javadoug                                 git@github.com:javadoug/jquery.sparkline.git                                     $# $@
register_remote lib/jquery-sparkline                                          jisaacks                                 git@github.com:jisaacks/jquery.sparkline.git                                     $# $@
register_remote lib/jquery-sparkline                                          jledoux                                  git@github.com:jledoux/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline                                          kapusta                                  git@github.com:kapusta/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline                                          local-original                           ../../../jquery-sparkline                                                        $# $@
register_remote lib/jquery-sparkline                                          solenoid                                 git@github.com:solenoid/jquery.sparkline.git                                     $# $@
register_remote lib/jquery-sparkline                                          ssclift                                  git@github.com:ssclift/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline                                          takacsv                                  git@github.com:takacsv/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline                                          timtucker                                git@github.com:timtucker/jquery.sparkline.git                                    $# $@
register_remote lib/jquery-sparkline                                          tnt-dev                                  git@github.com:tnt-dev/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline                                          vumaasha                                 git@github.com:vumaasha/jquery.sparkline.git                                     $# $@
register_remote lib/jquery-sparkline                                          vumasha                                  git@github.com:vumasha/jquery.sparkline.git                                      $# $@
register_remote lib/jquery-sparkline/lib/rainbow-vis                          anomal-original                          git@github.com:anomal/RainbowVis-JS.git                                          $# $@
register_remote lib/jquery-sparkline/lib/rainbow-vis                          manleyjster                              git@github.com:manleyjster/RainbowVis-JS.git                                     $# $@
register_remote lib/jquery-sparkline/lib/rainbow-vis                          stoimen                                  git@github.com:stoimen/RainbowVis-JS.git                                         $# $@
register_remote lib/keymaster                                                 ADstruc                                  git@github.com:ADstruc/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 Crisfole                                 git@github.com:Crisfole/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 GerHobbelt                               git@github.com:GerHobbelt/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 HenrikJoreteg                            git@github.com:HenrikJoreteg/keymaster.git                                       $# $@
register_remote lib/keymaster                                                 Skookum                                  git@github.com:Skookum/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 Xiaoli                                   git@github.com:Xiaoli/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 aeosynth                                 git@github.com:aeosynth/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 bfirsch                                  git@github.com:bfirsch/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 bfirsh                                   git@github.com:bfirsh/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 blented                                  git@github.com:blented/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 bosgood                                  git@github.com:bosgood/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 brianmcallister                          git@github.com:brianmcallister/keymaster.git                                     $# $@
register_remote lib/keymaster                                                 burl                                     git@github.com:burl/keymaster.git                                                $# $@
register_remote lib/keymaster                                                 c-rack                                   git@github.com:c-rack/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 captainclam                              git@github.com:captainclam/keymaster.git                                         $# $@
register_remote lib/keymaster                                                 ciaranj                                  git@github.com:ciaranj/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 cmawhorter                               git@github.com:cmawhorter/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 danielweck                               git@github.com:danielweck/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 dsc                                      git@github.com:dsc/keymaster.git                                                 $# $@
register_remote lib/keymaster                                                 dubrowgn                                 git@github.com:dubrowgn/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 epeli                                    git@github.com:epeli/keymaster.git                                               $# $@
register_remote lib/keymaster                                                 evidenceprime                            git@github.com:evidenceprime/keymaster.git                                       $# $@
register_remote lib/keymaster                                                 feross                                   git@github.com:feross/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 fizker                                   git@github.com:fizker/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 fkeymaster                               git@github.com:fkeymaster/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 fluxsaas                                 git@github.com:fluxsaas/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 garth                                    git@github.com:garth/keymaster.git                                               $# $@
register_remote lib/keymaster                                                 harvesthq                                git@github.com:harvesthq/keymaster.git                                           $# $@
register_remote lib/keymaster                                                 ian7                                     git@github.com:ian7/keymaster.git                                                $# $@
register_remote lib/keymaster                                                 informaat-ipe                            git@github.com:informaat-ipe/keymaster.git                                       $# $@
register_remote lib/keymaster                                                 inkie                                    git@github.com:inkie/keymaster.git                                               $# $@
register_remote lib/keymaster                                                 ioninteractive                           git@github.com:ioninteractive/keymaster.git                                      $# $@
register_remote lib/keymaster                                                 jamesarosen                              git@github.com:jamesarosen/keymaster.git                                         $# $@
register_remote lib/keymaster                                                 janitor                                  git@github.com:janitor/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 jasonm                                   git@github.com:jasonm/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 johnjbarton                              git@github.com:johnjbarton/keymaster.git                                         $# $@
register_remote lib/keymaster                                                 josephcp                                 git@github.com:josephcp/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 kentcdodds                               git@github.com:kentcdodds/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 lepture                                  git@github.com:lepture/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 local-original                           ../../../keymaster                                                               $# $@
register_remote lib/keymaster                                                 madrobby                                 git@github.com:madrobby/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 madrobby-original                        git@github.com:madrobby/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 map7                                     git@github.com:map7/keymaster.git                                                $# $@
register_remote lib/keymaster                                                 mrmarktyy                                git@github.com:mrmarktyy/keymaster.git                                           $# $@
register_remote lib/keymaster                                                 nguyenkha                                git@github.com:nguyenkha/keymaster.git                                           $# $@
register_remote lib/keymaster                                                 nopnop                                   git@github.com:nopnop/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 novaugust                                git@github.com:novaugust/keymaster.git                                           $# $@
register_remote lib/keymaster                                                 nwinkler                                 git@github.com:nwinkler/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 orloffv                                  git@github.com:orloffv/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 paales                                   git@github.com:paales/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 pombredanne                              git@github.com:pombredanne/keymaster.git                                         $# $@
register_remote lib/keymaster                                                 popomore                                 git@github.com:popomore/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 pthrasher                                git@github.com:pthrasher/keymaster.git                                           $# $@
register_remote lib/keymaster                                                 raine                                    git@github.com:raine/keymaster.git                                               $# $@
register_remote lib/keymaster                                                 secondplanet                             git@github.com:secondplanet/keymaster.git                                        $# $@
register_remote lib/keymaster                                                 simonbetton                              git@github.com:simonbetton/keymaster.git                                         $# $@
register_remote lib/keymaster                                                 spmjs                                    git@github.com:spmjs/keymaster.git                                               $# $@
register_remote lib/keymaster                                                 stevenleeg                               git@github.com:stevenleeg/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 toekneestuck                             git@github.com:toekneestuck/keymaster.git                                        $# $@
register_remote lib/keymaster                                                 toots                                    git@github.com:toots/keymaster.git                                               $# $@
register_remote lib/keymaster                                                 transifex                                git@github.com:transifex/keymaster.git                                           $# $@
register_remote lib/keymaster                                                 twoRoger                                 git@github.com:twoRoger/keymaster.git                                            $# $@
register_remote lib/keymaster                                                 untwine                                  git@github.com:untwine/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 urbany                                   git@github.com:urbany/keymaster.git                                              $# $@
register_remote lib/keymaster                                                 viff-service                             git@github.com:viff-service/keymaster.git                                        $# $@
register_remote lib/keymaster                                                 visionmedia                              git@github.com:visionmedia/keymaster.git                                         $# $@
register_remote lib/keymaster                                                 voxmachina                               git@github.com:voxmachina/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 windyarts                                git@github.com:windyarts/keymaster.git                                           $# $@
register_remote lib/keymaster                                                 wynaway                                  git@github.com:wynaway/keymaster.git                                             $# $@
register_remote lib/keymaster                                                 yangjunjun                               git@github.com:yangjunjun/keymaster.git                                          $# $@
register_remote lib/keymaster                                                 ysmood                                   git@github.com:ysmood/keymaster.git                                              $# $@
register_remote lib/slickgrid-checkbox-select-all-column-plugin               local-original                           ../../../slickgrid-checkbox-select-all-column-plugin                             $# $@
register_remote lib/slickgrid-checkbox-select-all-column-plugin               millerjb-original                        git@github.com:millerjb/SlickGrid.CheckboxSelectAllColumn.git                    $# $@
register_remote lib/slickgrid-enhanced-pager-plugin                           kingleema-original                       git@github.com:kingleema/SlickGridEnhancementPager.git                           $# $@
register_remote lib/slickgrid-enhanced-pager-plugin                           local-original                           ../../../slickgrid-enhanced-pager-plugin                                         $# $@
register_remote lib/slickgrid-guriddo-frozencolumns                           kahwee-original                          git@github.com:kahwee/guriddo.git                                                $# $@
register_remote lib/slickgrid-guriddo-frozencolumns                           local-original                           ../../../slickgrid-guriddo-frozencolumns                                         $# $@
register_remote lib/slickgrid-spreadsheet-plugins                             danny-sg-original                        git@github.com:danny-sg/slickgrid-spreadsheet-plugins.git                        $# $@
register_remote lib/slickgrid-spreadsheet-plugins                             jcsjcs                                   git@github.com:jcsjcs/slickgrid-spreadsheet-plugins.git                          $# $@
register_remote lib/slickgrid-spreadsheet-plugins                             local-original                           ../../../slickgrid-spreadsheet-plugins                                           $# $@
register_remote lib/slickgrid-surge-extensions                                local-original                           ../../../slickgrid-surge-extensions                                              $# $@
register_remote lib/slickgrid-surge-extensions                                surgeforward-original                    git@github.com:surgeforward/Surge-SlickGrid-Extensions.git                       $# $@
register_remote lib/slickgrid-surge-extensions                                togakangaroo                             git@github.com:togakangaroo/Surge-SlickGrid-Extensions.git                       $# $@
register_remote lib/slickgrid-totals-plugin                                   local-original                           ../../../slickgrid-totals-plugin                                                 $# $@
register_remote lib/slickgrid-totals-plugin                                   paynen-original                          git@github.com:paynen/slickgrid-totals-plugin.git                                $# $@
register_remote lib/spectrum                                                  AaronSherman                             git@github.com:AaronSherman/spectrum.git                                         $# $@
register_remote lib/spectrum                                                  Dodo-87                                  git@github.com:Dodo-87/spectrum.git                                              $# $@
register_remote lib/spectrum                                                  NetCrafters                              git@github.com:NetCrafters/spectrum.git                                          $# $@
register_remote lib/spectrum                                                  adambullmer                              git@github.com:adambullmer/spectrum.git                                          $# $@
register_remote lib/spectrum                                                  afronski                                 git@github.com:afronski/spectrum.git                                             $# $@
register_remote lib/spectrum                                                  andyburke                                git@github.com:andyburke/spectrum.git                                            $# $@
register_remote lib/spectrum                                                  bgrins-original                          git@github.com:bgrins/spectrum.git                                               $# $@
register_remote lib/spectrum                                                  bolster                                  git@github.com:bolster/spectrum.git                                              $# $@
register_remote lib/spectrum                                                  brynbellony                              git@github.com:brynbellony/spectrum.git                                          $# $@
register_remote lib/spectrum                                                  jholt456                                 git@github.com:jholt456/spectrum.git                                             $# $@
register_remote lib/spectrum                                                  jscheid                                  git@github.com:jscheid/spectrum.git                                              $# $@
register_remote lib/spectrum                                                  kristw                                   git@github.com:kristw/spectrum.git                                               $# $@
register_remote lib/spectrum                                                  local-original                           ../../../spectrum                                                                $# $@
register_remote lib/spectrum                                                  micschk                                  git@github.com:micschk/spectrum.git                                              $# $@
register_remote lib/spectrum                                                  niklasf                                  git@github.com:niklasf/spectrum.git                                              $# $@
register_remote lib/spectrum                                                  ottis                                    git@github.com:ottis/spectrum.git                                                $# $@
register_remote lib/spectrum                                                  owiber                                   git@github.com:owiber/spectrum.git                                               $# $@
register_remote lib/spectrum                                                  plepe                                    git@github.com:plepe/spectrum.git                                                $# $@
register_remote lib/spectrum                                                  rogerz                                   git@github.com:rogerz/spectrum.git                                               $# $@
register_remote lib/spectrum                                                  siliconjohn                              git@github.com:siliconjohn/spectrum.git                                          $# $@
register_remote lib/spectrum                                                  skoenen                                  git@github.com:skoenen/spectrum.git                                              $# $@
register_remote lib/spectrum                                                  slickgrid-dep-original                   ../../../spectrum                                                                $# $@
register_remote lib/spectrum                                                  stu-blair                                git@github.com:stu-blair/spectrum.git                                            $# $@
register_remote lib/spectrum                                                  vincentcr                                git@github.com:vincentcr/spectrum.git                                            $# $@
register_remote lib/spectrum                                                  vuzum                                    git@github.com:vuzum/spectrum.git                                                $# $@
register_remote lib/spectrum                                                  wallenium                                git@github.com:wallenium/spectrum.git                                            $# $@
register_remote lib/spectrum/lib/TinyColor                                    bgrins-original                          git@github.com:bgrins/TinyColor.git                                              $# $@
register_remote lib/spectrum/lib/TinyColor                                    local-master-original                    ../../../../../TinyColor/                                                        $# $@
register_remote lib/spectrum/lib/TinyColor                                    local-original                           ../../../TinyColor/                                                              $# $@
register_remote lib/threedubmedia                                             FlightDataServices                       git@github.com:FlightDataServices/jquery.threedubmedia.git                       $# $@
register_remote lib/threedubmedia                                             GerHobbelt                               git@github.com:GerHobbelt/jquery.threedubmedia.git                               $# $@
register_remote lib/threedubmedia                                             TheCloudlessSky                          git@github.com:TheCloudlessSky/jquery.threedubmedia.git                          $# $@
register_remote lib/threedubmedia                                             devongovett-eventdrag                    git@github.com:devongovett/jquery.event.drag.git                                 $# $@
register_remote lib/threedubmedia                                             dextermilo                               git@github.com:dextermilo/jquery.threedubmedia.git                               $# $@
register_remote lib/threedubmedia                                             eddanger                                 git@github.com:eddanger/jquery.threedubmedia.git                                 $# $@
register_remote lib/threedubmedia                                             foundry-modules                          git@github.com:foundry-modules/event.git                                         $# $@
register_remote lib/threedubmedia                                             gaarf                                    git@github.com:gaarf/jquery.event.drag-drop.git                                  $# $@
register_remote lib/threedubmedia                                             jschao                                   git@github.com:jschao/jquery.threedubmedia.git                                   $# $@
register_remote lib/threedubmedia                                             kindy                                    git@github.com:kindy/jquery.threedubmedia.git                                    $# $@
register_remote lib/threedubmedia                                             local-original                           ../../../jquery-event-drag-drop/                                                 $# $@
register_remote lib/threedubmedia                                             master-submodule                         ../../../jquery-event-drag-drop/                                                 $# $@
register_remote lib/threedubmedia                                             master-submodule-original                ../../../jquery-event-drag-drop/                                                 $# $@
register_remote lib/threedubmedia                                             mindmatters                              git@github.com:mindmatters/jquery.threedubmedia.git                              $# $@
register_remote lib/threedubmedia                                             richardscarrott                          git@github.com:richardscarrott/jquery.threedubmedia.git                          $# $@
register_remote lib/threedubmedia                                             risicle                                  git@github.com:risicle/jquery.threedubmedia.git                                  $# $@
register_remote lib/threedubmedia                                             ryanramage                               git@github.com:ryanramage/jquery.threedubmedia.git                               $# $@
register_remote lib/threedubmedia                                             sambaker                                 git@github.com:sambaker/jquery.threedubmedia.git                                 $# $@
register_remote lib/threedubmedia                                             slickgrid-submodule                      ../slickgrid/lib/threedubmedia/                                                  $# $@
register_remote lib/threedubmedia                                             slickgrid-submodule-original             ../slickgrid/lib/threedubmedia/                                                  $# $@
register_remote lib/threedubmedia                                             sortex                                   git@github.com:sortex/jquery.threedubmedia.git                                   $# $@
register_remote lib/threedubmedia                                             soundtrackyourbrand                      git@github.com:soundtrackyourbrand/jquery.threedubmedia.git                      $# $@
register_remote lib/threedubmedia                                             thegrandpoobah                           git@github.com:thegrandpoobah/jquery.threedubmedia.git                           $# $@
register_remote lib/threedubmedia                                             threedubmedia-original                   git@github.com:threedubmedia/jquery.threedubmedia.git                            $# $@
register_remote lib/verge-screendimensions                                    local-1-original                         ../jquery-verge/                                                                 $# $@
register_remote lib/verge-screendimensions                                    local-original                           ../../../verge-screendimensions                                                  $# $@
register_remote lib/verge-screendimensions                                    ryanve-original                          git@github.com:ryanve/verge.git                                                  $# $@



popd                                                                            2> /dev/null   > /dev/null

